version: '3.3'
services:
  # api:
  #   container_name: 'api'
  #   build: './api'
  #   ports:
  #     - '8080:8080'
  #   volumes:
  #     - './api:/go/src/app'
  #   depends_on:
  #     - 'mongo'
  # web:
  #   container_name: 'web'
  #   image: 'nginx:latest'
  #   ports:
  #     - '8081:80'
  #   volumes:
  #     - './web:/usr/share/nginx/html'
  #   depends_on:
  #     - 'api'
  mongo_db:
      image: mongo:3.3
      ports:
        - target: 27017
          published: 27017
          protocol: tcp
          mode: host
      volumes:
        - type: bind
          source: ./backup
          target: /backup